version: '3'

services:

  nginx:
    image: poktnetwork/nginx:dispatch
    build: ../nginx/
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "../nginx/conf.d/10-pocket.conf:/etc/nginx/conf.d/default.conf"
      - "../nginx/nginx.conf:/etc/nginx/nginx.conf"

    networks:
      - pocket
  
  pivx-mainnet:
    image: poktnetwork/pivx
    build:
      context: .
      args:
        VERSION: 3.4.0
      dockerfile: Dockerfile
    command: -server -rest -smsg -printtoconsole -logtimestamps -logips -rpccorsdomain="*" -rpcbind="0.0.0.0" -rpcallowip="0.0.0.0/0" 
    volumes:
      - pivx-mainnet:/root/.pivx
    expose:
      - "51473"
    networks:
      - pocket
  
  pivx-testnet:
    image: poktnetwork/pivx
    build:
      context: .
      args:
        VERSION: 3.4.0
      dockerfile: Dockerfile
    command: -testnet -server -rest -smsg -printtoconsole -logtimestamps -logips -rpccorsdomain="*" -rpcbind="0.0.0.0" -rpcallowip="0.0.0.0/0" 
    volumes:
      - pivx-testnet:/root/.pivx
    expose:
      - "51475"
    networks:
      - pocket

  pocket-service:
    image: poktnetwork/pocket-core:stagenet-latest
    ports:
      - "8081:8081"
      - "26656:26656"
    expose:
      - 26656
      - 8081
    command: pocket start
    environment:
      POCKET_CORE_KEY: <private key>
      POCKET_CORE_PASSPHRASE: <passphrase>
    volumes:
      - ../configs:/home/app/.pocket/config
      - ./chains.json:/home/app/.pocket/config/chains.json
    networks:
      - pocket

volumes:
  pivx-mainnet:
  pivx-testnet:

networks:
  pocket:
    driver: bridge
