version: '3'

services:

  nginx:
    image: poktnetwork/nginx:dispatch
    build: ../nginx/
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "../nginx/conf.d/10-pocket.conf:/etc/nginx/conf.d/default.conf"
      - "../nginx/nginx.conf:/etc/nginx/nginx.conf"
    networks:
      - pocket

  # https://zcoin.io/znodes-specifications-release-founders-rewards-reduction/
  zcoin-mainnet:
    image: zcoinofficial/zcoind 
    command: -server -rest -listen -whitelist=0.0.0.0 -rpcallowip=0.0.0.0  
    volumes:
      - zcoin-mainnet:/home/zcoind/.zcoin
    expose:
      - "8888"
      - "8168"
    networks:
      - pocket

  pocket-service:
    image: poktnetwork/pocket-core:stagenet-latest
    ports:
      - "8081:8081"
      - "26656:26656"
    expose:
      - 26656
      - 8081
    command: pocket start --simulateRelay
    environment:
      POCKET_CORE_KEY: b8a56dead392e2b57eaba988068d0cedc0a11b9a16ca9610b094ec31a9cbc06650220553e5ccf56a863eaed88ebf1487e1dcb20e7fffbe0fb841cab1bb76af4d
      POCKET_CORE_PASSPHRASE: yo 
    volumes:
      - ../configs:/home/app/.pocket/config
      - ./chains.json:/home/app/.pocket/config/chains.json
    networks:
      - pocket

volumes:
  zcoin-mainnet:

networks:
  pocket:
    driver: bridge
