version: '3'

services:

  nginx:
    image: poktnetwork/nginx:dispatch
    build: ../nginx/
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "../nginx/conf.d/10-pocket.conf:/etc/nginx/conf.d/default.conf"
      - "../nginx/nginx.conf:/etc/nginx/nginx.conf"

    networks:
      - pocket

  # https://docs.wavesplatform.com/en/waves-node/how-to-install-a-node/how-to-install-a-node.html 
  waves-mainnet:
    image: wavesplatform/wavesnode 
    environment:
        WAVES_NETWORK: "MAINNET"
        WAVES_HEAP_SIZE: "2g"
        WAVES_LOG_LEVEL: "INFO"
        WAVES_WALLET_PASSWORD: "MVP_GCP_ANY_PASSWORD"
        JAVA_OPTS: "-Dwaves.network.declared-address=0.0.0.0:6868 -Dwaves.rest-api.port=6870 -Dwaves.rest-api.bind-address=0.0.0.0 -Dwaves.rest-api.enable=yes"

    volumes:
      - waves-mainnet:/var/lib/waves
    expose:
      - "6869"
      - "6868"
    networks:
      - pocket

  pocket-service:
    image: poktnetwork/pocket-core:stagenet-latest
    ports:
      - "8081:8081"
      - "26656:26656"
    expose:
      - 26656
      - 8081
    command: pocket start --simulateRelay
    environment:
      POCKET_CORE_KEY: b8a56dead392e2b57eaba988068d0cedc0a11b9a16ca9610b094ec31a9cbc06650220553e5ccf56a863eaed88ebf1487e1dcb20e7fffbe0fb841cab1bb76af4d
      POCKET_CORE_PASSPHRASE: yo 
    volumes:
      - ../configs:/home/app/.pocket/config
      - ./chains.json:/home/app/.pocket/config/chains.json
    networks:
      - pocket

volumes:
  waves-mainnet:

networks:
  pocket:
    driver: bridge
