version: '3'

services:

  nginx:
    image: poktnetwork/nginx:dispatch
    build: ../nginx/
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "../nginx/conf.d/10-pocket.conf:/etc/nginx/conf.d/default.conf"
      - "../nginx/nginx.conf:/etc/nginx/nginx.conf"
    
    networks:
      - pocket

  tezos-mainnet:
    image: tezos/tezos:mainnet
    expose:
      - '8732'
      - '9732'
    volumes:
      - mainnet-node-data:/var/run/tezos/node
      - mainnet-client-data:/var/run/tezos/client
    
    command: tezos-node
    networks:
      - pocket

  tezos-alphanet:
    image: tezos/tezos:babylonnet
    expose:
      - '8732'
      - '9732'
    volumes:
      - alphanet-node-data:/var/run/tezos/node
      - alphanet-client-data:/var/run/tezos/client
    
    command: tezos-node
    networks:
      - pocket

  pocket-service:
    image: poktnetwork/pocket-core:stagenet-latest
    ports:
      - "8081:8081"
      - "26656:26656"
    expose:
      - 26656
      - 8081
    command: pocket start
    environment:
      POCKET_CORE_KEY: <private key>
      POCKET_CORE_PASSPHRASE: <passphrase>
    volumes:
      - ../configs:/home/app/.pocket/config
      - ./chains.json:/home/app/.pocket/config/chains.json
    networks:
      - pocket

volumes:
  alphanet-client-data:
  alphanet-node-data:
  mainnet-client-data:
  mainnet-node-data:

networks:
  pocket:
    driver: bridge
