version: '2.1'

services:

  geth-rinkeby:
    image: ethereum/client-go:v1.9.13
    expose:
      - "8545"
      - "8546"
      - "30303"
    volumes:
      - geth-rinkeby:/.rinkeby
    command: "--rinkeby --rpc --rpcapi eth,net --rpcaddr 0.0.0.0 --rpcport 8545 --rpcvhosts=* --syncmode fast --datadir .rinkeby --verbosity 3"
    networks:
      - pocket

  geth-mainnet:
    image: ethereum/client-go:v1.9.13
    expose:
      - "8545"
      - "8546"
      - "30303"
    volumes:
      - geth-mainnet:/.mainnet
    command: "--rpc  --rpcapi eth,net --rpcaddr 0.0.0.0 --rpcport 8545 --rpcvhosts=* --syncmode fast --datadir .mainnet --verbosity 3"
    networks:
      - pocket

  pocket-service:
    image: poktnetwork/pocket-core:stagenet-latest
    ports:
      - "8081:8081"
      - "26656:26656"
    expose:
      - 26656
      - 8081
    command: pocket start
    environment:
      POCKET_CORE_KEY: b8a56dead392e2b57eaba988068d0cedc0a11b9a16ca9610b094ec31a9cbc06650220553e5ccf56a863eaed88ebf1487e1dcb20e7fffbe0fb841cab1bb76af4d
      POCKET_CORE_PASSPHRASE: yo 
    volumes:
      - ../configs:/home/app/.pocket/config
      - ./chains.json:/home/app/.pocket/config/chains.json
    networks:
      - pocket

volumes:
  geth-mainnet:
  geth-rinkeby:

networks:
  pocket:
    driver: bridge
