version: "2.2"
services:
    prep-node:
        image: 'iconloop/prep-node:2001091813x7eba36-dev'
        container_name: "prep-testnet"
        restart: "always"
        environment:
          LOOPCHAIN_LOG_LEVEL: "DEBUG"
          ICON_LOG_LEVEL: "DEBUG"
          DEFAULT_PATH: "/data/loopchain"
          LOG_OUTPUT_TYPE: "file"
          PRIVATE_PATH: "/cert/key"
          PRIVATE_PASSWORD: "qwer1234!"
          CERT_PATH: "/cert"
          SERVICE: "zicon"
          FASTEST_START: "yes"
        cap_add:
          - SYS_TIME
        volumes:
          - ./data:/data
          - ./cert:/cert:ro
        ports:
          - '7100:7100'
          - '9000:9000'
        expose:
          - "7100"
          - "9000"
        networks:
          - pocket
    ubuntu:
        image: ubuntu:18.04
        networks:
            - pocket
        command: /bin/bash -c "sleep 36000"
  pocket-service:
    image: poktnetwork/pocket-core:stagenet-latest
    ports:
      - "8081:8081"
      - "26656:26656"
    expose:
      - 26656
      - 8081
    command: pocket start
    environment:
      POCKET_CORE_KEY: b8a56dead392e2b57eaba988068d0cedc0a11b9a16ca9610b094ec31a9cbc06650220553e5ccf56a863eaed88ebf1487e1dcb20e7fffbe0fb841cab1bb76af4d
      POCKET_CORE_PASSPHRASE: yo 
    volumes:
      - ../configs:/home/app/.pocket/config
      - ./chains.json:/home/app/.pocket/config/chains.json
    networks:
      - pocket
networks:
    pocket:
        driver: bridge
