version: '3'

services:

  nginx:
    image: poktnetwork/nginx:dispatch
    build: ../nginx/
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "../nginx/conf.d/10-pocket.conf:/etc/nginx/conf.d/default.conf"
      - "../nginx/nginx.conf:/etc/nginx/nginx.conf"

    networks:
      - pocket

  POA-testnet:
    image: poktnetwork/poa-node:sokol
    build:
      context: .
      dockerfile: Dockerfile
      args:
        chain: 'sokol'
    expose:
      - "8545"
      - "8546"
      - "30303"
    volumes:
      - POA-testnet:/home/parity/.ethereum
    
    command: --base-path .ethereum --chain ./poa-chain-spec/spec.json --reserved-peers ./poa-chain-spec/bootnodes.txt --port 30303 --jsonrpc-hosts all --jsonrpc-cors all --jsonrpc-interface all --ipc-apis web3,net,eth,pubsub,parity,parity_pubsub,traces,rpc,shh,shh_pubsub  --ws-interface all --ws-hosts all --ws-origins all --ws-apis web3,net,eth,pubsub,parity,parity_pubsub,traces,rpc,shh,shh_pubsub --interface all
    networks:
      - pocket

  POA-kovan:
    image: poktnetwork/poa-node:kovan
    build:
      context: .
      dockerfile: Dockerfile
      args:
        chain: 'kovan'
    expose:
      - "8545"
      - "8546"
      - "30303"
    volumes:
      - POA-testnet:/home/parity/.ethereum
    
    command: --base-path .ethereum --chain ./poa-chain-spec/spec.json --reserved-peers ./poa-chain-spec/bootnodes.txt --port 30303 --jsonrpc-hosts all --jsonrpc-cors all --jsonrpc-interface all --ipc-apis web3,net,eth,pubsub,parity,parity_pubsub,traces,rpc,shh,shh_pubsub  --ws-interface all --ws-hosts all --ws-origins all --ws-apis web3,net,eth,pubsub,parity,parity_pubsub,traces,rpc,shh,shh_pubsub --interface all
    networks:
      - pocket


  POA-xdai:
    image: poktnetwork/poa-node:xdai
    build:
      context: .
      dockerfile: Dockerfile
      args:
        chain: 'dai'
    expose:
      - "8545"
      - "8546"
      - "30303"
    volumes:
      - POA-xdai:/home/parity/.ethereum

    command: --base-path .ethereum --chain ./poa-chain-spec/spec.json --reserved-peers ./poa-chain-spec/bootnodes.txt --port 30303 --jsonrpc-hosts all --jsonrpc-cors all --jsonrpc-interface all --ipc-apis web3,net,eth,pubsub,parity,parity_pubsub,traces,rpc,shh,shh_pubsub  --ws-interface all --ws-hosts all --ws-origins all --ws-apis web3,net,eth,pubsub,parity,parity_pubsub,traces,rpc,shh,shh_pubsub --interface all 
    networks:
      - pocket
      
  POA-mainnet:
    image: poktnetwork/poa-node:core
    build:
      context: .
      dockerfile: Dockerfile
      args:
        chain: 'core'
    expose:
      - "8545"
      - "8546"
      - "30303"
    volumes:
      - POA-mainnet:/home/parity/.ethereum
    
    command: --base-path .ethereum --chain ./poa-chain-spec/spec.json --reserved-peers ./poa-chain-spec/bootnodes.txt --port 30303 --jsonrpc-hosts all --jsonrpc-cors all --jsonrpc-interface all --ipc-apis web3,net,eth,pubsub,parity,parity_pubsub,traces,rpc,shh,shh_pubsub  --ws-interface all --ws-hosts all --ws-origins all --ws-apis web3,net,eth,pubsub,parity,parity_pubsub,traces,rpc,shh,shh_pubsub --interface all 
    networks:
      - pocket

  pocket-service:
    image: poktnetwork/pocket-core:stagenet-latest
    ports:
      - "8081:8081"
      - "26656:26656"
    expose:
      - 26656
      - 8081
    command: pocket start
    environment:
      POCKET_CORE_KEY: <private key>
      POCKET_CORE_PASSPHRASE: <passphrase>
    volumes:
      - ../configs:/home/app/.pocket/config
      - ./chains.json:/home/app/.pocket/config/chains.json
    networks:
      - pocket

volumes:
  POA-mainnet:
  POA-testnet:
  POA-xdai:

networks:
  pocket:
    driver: bridge
