version: '2.1'

services:

  algorand-testnet:
    image: poktnetwork/algorand:2.0.6-testnet 
    build:
      context: . 
      dockerfile: Dockerfile.testnet 
    expose:
      - "8080"
    volumes:
      - ./command.sh:/root/node/command.sh
      - algorand-testnet:/root/node/.data/
      - ./config_testnet.json:/root/node/data/config.json
    entrypoint: bash
    command: command.sh
    environment:
      NETWORK: "testnet"
    networks:
      - pocket

  algorand-mainnet:
    image: poktnetwork/algorand:2.0.6-mainnet
    build:
      context: . 
      dockerfile: Dockerfile 
    expose:
      - "8080"
    volumes:
      - ./command.sh:/root/node/command.sh
      - algorand-mainnet:/root/node/.data/
      - ./config_mainnet.json:/root/node/data/config.json
    entrypoint: bash
    command: command.sh
    networks:
      - pocket
 
  pocket-core-testnet:
    image: poktnetwork/pocket-core:${ENV:-staging-latest}

    privileged: true
    command: "pocket start --seeds f31f77c8a882504ef8525e6557351295107f1680@10.20.4.109:26656 --blockTime=1"
    expose:
      - "8081"  #  POKT RPC
      - "26657" #  Tendermint RPC
      - "26656" #  Tendermint Peers
      - "46656" #  Tendermint Peers
    environment:
      POCKET_CORE_KEY: "b8a56dead392e2b57eaba988068d0cedc0a11b9a16ca9610b094ec31a9cbc06650220553e5ccf56a863eaed88ebf1487e1dcb20e7fffbe0fb841cab1bb76af4d"
      POCKET_CORE_PASSPHRASE: "yo"

    volumes:
        - "./chains.json:/home/app/.pocket/chains.json"
        - "./genesis.json:/home/app/.pocket/genesis.json"
    networks:
      - pocket

volumes:
  algorand-mainnet:
  algorand-testnet:

networks:
  pocket:
    driver: bridge
