version: '3'

services:
  aion-mainnet:
    image: poktnetwork/aionr:mainnet-1.3.0
    command: "./mainnet.sh"
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        AION_NETWORK: "mainnet" 
    expose:
      - "8545"
      - "8547"
      - "30303"
    volumes:
      - aion-mainnet:/root/.aion
    environment:
      AIONR_HOME: "/aionr/mainnet"
      java_api_listen_address: "0.0.0.0"
      rpc_listen_address: "0.0.0.0"
      AION_NETWORK: "mainnet"
    networks:
      - pocket

  aion-mastery:
    image: poktnetwork/aionr:mastery-1.3.0 
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        AION_NETWORK: "mastery" 
    command: "./mastery.sh" 
    expose:
      - "8545"
      - "8547"
      - "30303"
    volumes:
      - aion-mastery:/root/.aion
    
    environment:
      AIONR_HOME: "/aionr/mastery"
      java_api_listen_address: "0.0.0.0"
      rpc_listen_address: "0.0.0.0"
      AION_NETWORK: "mastery" 
    networks:
      - pocket

  pocket-service:
    image: poktnetwork/pocket-core:stagenet-latest
    ports:
      - "8081:8081"
      - "26656:26656"
    expose:
      - 26656
      - 8081
    command: pocket start
    environment:
      POCKET_CORE_KEY: <private key>
      POCKET_CORE_PASSPHRASE: <passphrase>
    volumes:
      - ../configs:/home/app/.pocket/config
      - ./chains.json:/home/app/.pocket/config/chains.json
    networks:
      - pocket

volumes:
  aion-mainnet:
  aion-mastery:

networks:
  pocket:
    driver: bridge
