version: '3'

services:

  nginx:
    image: poktnetwork/nginx:dispatch
    build: ../nginx/
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "../nginx/conf.d/10-pocket.conf:/etc/nginx/conf.d/default.conf"
      - "../nginx/nginx.conf:/etc/nginx/nginx.conf"

    networks:
      - pocket

  # https://docs.wavesplatform.com/en/waves-node/how-to-install-a-node/how-to-install-a-node.html 
  daps-mainnet:
    image: poktnetwork/daps:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MAJOR_VERSION: 1.0.5
        SPECIFIC_VERSION: 1.0.5.7
    command: -listen -rest -server -printtoconsole -logtimestamps -logips -rpccorsdomain="*" -rpcbind="0.0.0.0" -rpcallowip="0.0.0.0/0"  
    volumes:
      - daps-mainnet:/home/DAPS_user/.dapscoin
    expose:
      - "53573"
    networks:
      - pocket

  pocket-service:
    image: poktnetwork/pocket-core:stagenet-latest
    ports:
      - "8081:8081"
      - "26656:26656"
    expose:
      - 26656
      - 8081
    command: pocket start
    environment:
      POCKET_CORE_KEY: b8a56dead392e2b57eaba988068d0cedc0a11b9a16ca9610b094ec31a9cbc06650220553e5ccf56a863eaed88ebf1487e1dcb20e7fffbe0fb841cab1bb76af4d
      POCKET_CORE_PASSPHRASE: yo 
    volumes:
      - ../configs:/home/app/.pocket/config
      - ./chains.json:/home/app/.pocket/config/chains.json
    networks:
      - pocket

volumes:
  daps-mainnet:

networks:
  pocket:
    driver: bridge
